version: "3.8"
services:
  tfserve:
    image: tensorflow/serving
    ports:
      - "8500:8500"
      - "8501:8501"
    environment:
      - MODEL_NAME=dx-classifier
    volumes:
      - ~/ml/dx-classifier:/models/dx-classifier